<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description>Suite kiểm thử chức năng Quản lý bài tập Admin - TC_01 đến TC_10</description>
   <n>suite_QuanLyBaiTap</n>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>suite-quan-ly-bai-tap-001</testSuiteGuid>
   <testCaseLink>
      <guid>tc-link-quan-ly-bai-tap-001</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_QuanLyBaiTap</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>BASE_URL</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ADMIN_USER</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ADMIN_PASS</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
