<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_ReadingListeningWritingSpeakingVocab_b1fef0</name>
   <tag></tag>
   <elementGuidId>3a43a3c3-1b9b-4dd7-a639-caebf3e6dfc8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='skill']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;skill&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>2123092e-8acf-4c7e-a6cd-dd112587f15e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>skill</value>
      <webElementGuid>7fdcf33d-ab9f-4c57-b527-c5f0d94f6be7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-cNFoqh bVyUIo</value>
      <webElementGuid>9fae8388-e4b1-44e3-9d59-40a4bf405312</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ReadingListeningWritingSpeakingVocabularyGrammarMixed</value>
      <webElementGuid>8c2ff58d-38ed-4a8f-a3f8-1db0d24d8f20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-gVrasc btEuEu&quot;]/div[@class=&quot;sc-nVSyK hTjewX&quot;]/div[@class=&quot;sc-gxDBpp klruer&quot;]/form[1]/div[@class=&quot;sc-gZtkdK kAjTll&quot;]/select[@class=&quot;sc-cNFoqh bVyUIo&quot;]</value>
      <webElementGuid>7c37a5b4-b79f-445e-a00b-6a516e753bc3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='skill']</value>
      <webElementGuid>5d3127e3-13ee-463c-94cc-2402033d761d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/div/form/div[4]/select</value>
      <webElementGuid>3c5fe9f7-03d0-49cb-a18c-c1d89ddde96b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kỹ năng cần tập trung'])[1]/following::select[1]</value>
      <webElementGuid>adc6bb47-f950-4ce7-94c5-8999cb2bf29c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loại mục tiêu'])[11]/following::select[2]</value>
      <webElementGuid>df76a265-b6bd-4657-a466-9d7e5bd99e01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Điểm số mục tiêu'])[1]/preceding::select[1]</value>
      <webElementGuid>8bd63f72-f6d2-4161-804f-9cc91c6b865a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hạn hoàn thành'])[1]/preceding::select[1]</value>
      <webElementGuid>abf16184-829a-4709-8c31-e422ce1d89ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/select</value>
      <webElementGuid>4de3ea23-a122-4cfd-9e24-5c7ebf4737ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'skill' and (text() = 'ReadingListeningWritingSpeakingVocabularyGrammarMixed' or . = 'ReadingListeningWritingSpeakingVocabularyGrammarMixed')]</value>
      <webElementGuid>788a2830-852e-4481-b245-bfeaa9d64bff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
