<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_To mi</name>
   <tag></tag>
   <elementGuidId>ca196c39-fb86-4dc2-82a9-e93999faae2a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.ikNLPT</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' ikNLPT ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4cccd3e8-ec89-4d20-b9d3-4b957a60ed72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>e6b7b54d-bf43-40f9-85fd-96d6c2875e27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-jjjXBm ikNLPT</value>
      <webElementGuid>dd545112-7b50-4ddd-a4ef-f547d8e5d11b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tạo mới</value>
      <webElementGuid>3c9abb2f-5d57-4616-b837-81c120377801</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-581a12894208d7b29c9002318a0903ce</value>
      <webElementGuid>641099c5-bfcb-4cae-a696-0bff1c2eaef1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' ikNLPT ')]</value>
      <webElementGuid>38cfe0d9-05b7-4dc1-9f8b-1e1b7e455ce0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' ikNLPT ')]</value>
      <webElementGuid>57e9dda4-f0f1-4444-8477-aff1e3652f93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Tạo mới' or . = 'Tạo mới')]</value>
      <webElementGuid>19755f72-d492-4079-a272-9814fb5aa686</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
